### ISSUE TITLE
HDF5 Files are missing xml info

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#141]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Frustratingly enough, there seems to have been an issue when downloading all the data that the response files weren't stored in the HDF5 files. Approximately a 1/4 of files have responses making the error absurd. I'm also thinking about a quick fix, because xml's have been downloaded to the station directory just not been added to the the HDF5 file grrr.

### Code to Reproduce

```python
r = Request(... format='hdf5')
r.download()
r.preprocess()
```

### Error Traceback

```Python traceback
ERROR:pyglimer.request.preprocess:Could not find station inventory for Station XO.KSN4
Traceback (most recent call last):
  File "/scratch/gpfs/lsawade/PyGLImER/src/pyglimer/waveform/preprocessh5.py", line 197, in _preprocessh5_single
    inv = rdb.get_response(net, stat)
  File "/scratch/gpfs/lsawade/PyGLImER/src/pyglimer/database/raw.py", line 234, in get_response
    with BytesIO(np.array(self[path], dtype=np.dtype('byte'))) as b:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/lsawade/.conda/envs/PyGLImER/lib/python3.10/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
```

### PyGLImER Version?

---

### Operating System?

linux

### Python Version?

3.10.6

### Installation Method?

developer installation / from source / git checkout

**Comment by lsawade** [comment]
Alright, after inspection, I see that this is explicitly set to ``False`` in the ``download_waveforms()`` function, but in the preprocess function there is no catch to load the response from the stations directory. Is this a feature or an oversight?

https://github.com/PyGLImER/PyGLImER/blob/038fea9717037ecfbe81e7c0e232fd0b48d7c181/src/pyglimer/waveform/download.py#L912

**Comment by lsawade** [comment]
As a quick fix, I made a script: 

```
#/bin/env python3

import sys
from pyglimer.database.raw import statxml_to_hdf5

statxml_to_hdf5(sys.argv[1], sys.argv[2])
```
 
I have a feeling that the inventory however is supposed to be written earlier, will continue to investigate.

**Comment by lsawade** [comment]
I believe I have found the issue. And it's simple not taking into account all stations at the end of the event loop. 

When `mseed_to_hdf5()` is called here

https://github.com/PyGLImER/PyGLImER/blob/038fea9717037ecfbe81e7c0e232fd0b48d7c181/src/pyglimer/waveform/download.py#L912

It does removes a large chunk of `mseed`s without ever adding the `stationxml`. At the end of the event loop when 

https://github.com/PyGLImER/PyGLImER/blob/038fea9717037ecfbe81e7c0e232fd0b48d7c181/src/pyglimer/waveform/download.py#L923

is called only a fraction of the available stations have actually `mseed`s left. Meaning, the recursive function ``mseed_to_hdf5()`` which depends on the availability of `mseed`s will only add stationxml to the station files that actually have `mseed`s remaining.

I think a fix would be to simple run
```python
statxml_to_hdf5(rawloc, statloc)
```
after `mseed_to_hdf5()`, and it should fix the problem. Compared to the time needed for downloading, the time it takes to add the stationxml to the HDF5 files is peanuts.

Please check this @PeterMakus, if you agree I'll push a fix, then merge, then I should be CCP stacking.

**Comment by PeterMakus** [comment]
Hi @lsawade ,

I guess we could do that. I am wondering though whether it will fix the problem. As I see it, all response information is downloaded and added to the hdf5 files here:

https://github.com/PyGLImER/PyGLImER/blob/038fea9717037ecfbe81e7c0e232fd0b48d7c181/src/pyglimer/waveform/download.py#L923

after executing

https://github.com/PyGLImER/PyGLImER/blob/038fea9717037ecfbe81e7c0e232fd0b48d7c181/src/pyglimer/waveform/download.py#L920

The reason for the latter line was to make sure that really all response information is added and not just a subset. For example, if station XY was active from 1970-2010, but the sensor was changed in 1990, it might download information for only one sensor if we only requested data from e.g. 1995 onwards.

Have you tried changing this line and checked whether it actually fixes the problem?

**Comment by lsawade** [comment]
Hi,

The full inventory is definitely downloaded and all the stationxml's are definitely there, but not added to the HDF5 files because this 
 
> only a fraction of the available stations have actually `mseed`s left. Meaning, the recursive function `mseed_to_hdf5()` which depends on the availability of `mseed`s will only add stationxml to the station files that actually have `mseed`s remaining.

problem remains. Because `mseed_to_hdf5()` which depends on the availability of `mseed`s and not on the availability of stationxml. If the last request does not have `mseed`s for certain stations. Those stations won't get a station xml at the end.

---

Question. Do you always download the entire station.xml, no matter what?

**Comment by PeterMakus** [comment]
Yes, the entire station.xml is always downloaded.

I guess the savest bet would be to alter ``mseed_to_hdf5``so that if ``statloc=True`` it will also check the availability of stationxmls and not only mseeds, what do you think?

**Comment by PeterMakus** [comment]
Ok,
turns out the only thing we have to do is add an ``overwrite`` flag to ``RawDatabase.add_response``. Because otherwise, they might contain outdated response files.

**Comment by lsawade** [comment]
Testing!
